version: '2'

services:
    mysql:
        image: mysql:5.7
        volumes:
            - "./.data/db:/var/lib/mysql"
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456
    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        expose:
            - 9000
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        depends_on:
            - mysql
    nginx:
        image: nginx
        volumes_from:
            - php
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        expose:
            - 80
        depends_on:
            - php

networks:
    default:
        external:
            name: nginx-reverse-proxy_default
